{% set name = "pytide" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d64df7850ab60b840a08c993a3f441d15194d4a810030df73fd345839f9e786e
build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv'
  skip: true  # [linux32 or win32 or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - vs2017_win-64          # [win]
    - cmake
  host:
    - eigen
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - pytide

about:
  home: https://github.com/CNES/pangeo-pytide
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'Tidal constituents analysis in Python.'

  description: |
    pytide allows to analyze the tidal constituents of a time series
    from a harmonic analysis. The definition of tidal constants and astronomical
    arguments is taken from FES2014 tidal prediction software.
  doc_url: https://pangeo-pytide.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pytide

extra:
  recipe-maintainers:
    - fbriol
