{% set name = "pytide" %}
{% set version = "1.2.5" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c452da3d2a1c45564e3205508f679dfc3f3f9888e84be32a93bcb219481b34f2
build:
  number: {{ build }}
  script: '{{ PYTHON }} -m pip install . -vv'
  skip: true  # [linux32 or win32 or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - make                   # [linux]
    - vs2017_win-64          # [win]
    - cmake
  host:
    - eigen
    - mkl-devel
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - mkl  # [linux or win]

test:
  imports:
    - pytide

about:
  home: https://github.com/CNES/pangeo-pytide
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tidal constituents analysis in Python.'

  description: |
    pytide allows to analyze the tidal constituents of a time series
    from a harmonic analysis. The definition of tidal constants and astronomical
    arguments is taken from FES2014 tidal prediction software.
  doc_url: https://pangeo-pytide.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pytide

extra:
  recipe-maintainers:
    - fbriol
