{% set name = "pytide" %}
{% set version = "1.2.7" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CNES/pangeo-{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a38eb4e3cc6aca4286d3a29ef36530660f02472b7c807427fa3ffb7a7bc870b
build:
  number: {{ build }}
  {% if target_platform == "win-64" %}
  script: {{ PYTHON }} -m pip install . -vv --global-option=build_ext --global-option="--generator=Visual Studio 17 2022"
  {% else %}
  script: {{ PYTHON }} -m pip install . -vv
  {% endif %}

  skip: true  # [linux32 or win32 or py<36]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux or osx]
    - make                   # [linux]
    - vs2017_win-64          # [win]
    - cmake
  host:
    - eigen
    - mkl-devel
    - numpy
    - pip
    - python
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - mkl  # [linux or win]

test:
  imports:
    - pytide

about:
  home: https://github.com/CNES/pangeo-pytide
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tidal constituents analysis in Python.'

  description: |
    pytide allows to analyze the tidal constituents of a time series
    from a harmonic analysis. The definition of tidal constants and astronomical
    arguments is taken from FES2014 tidal prediction software.
  doc_url: https://pangeo-pytide.readthedocs.io/
  dev_url: https://github.com/CNES/pangeo-pytide

extra:
  recipe-maintainers:
    - fbriol
