travis:
  secure:
    BINSTAR_TOKEN: Sk18fFUD4CgPDukLVx6RHCvpnTkrswl2+mABhFzdHrkdbLktkApc+OLSxVzkJw9fCyVrWpALYW+45/fqJpQFXAlcm2/lUmDXf/07Ogt4B5c2JqbPU7OaE4ZM1xpQL2Bi4zKxESBEFuAgfLHT8Sggfhk584VtEOjlH5LuAEVsmcbwJhyHyMmQYgCLoS6j4+t2Z8C8cpHoRWmcqTHEIF1Is3mWnYxGQL3NM5/FMcuUkNuy40lhCCVai6+oixpXAjyaANpbtK42XLQ/mu1VYZ/JdHiIH/z3ZsoYELS4cbLpzH5oCFrc+wQiBHbSdfHWcCwL0rDe4VtCGUxPS5eX7MnKltlXtHPXa6BWd6pHTWsrdQ8c2WIRBn8H8onPZE/6Pf/eybl8Rh+bYBIROpm0cv9JTix2od/cBFUHqgjcSoXex2BLKoSGVz4zkgGir+yQp30ox0iSsqVW4Z0FZzIUKjLua1Grbz+WyxAKBl4vTrJp2AOv7AiCsS7FwYsZoSKM+2AVcvGu9dE1Ua1Etlo2VyLUdteiIXZXMGi4DGnxTLFmmrB3YGjvxmt2Bnrbj8NxHx8jPUJITtkoCnMwef5LidddDFsL3NC/BiP3UIhBYtIAU+NeqoBOsVJeSiV79Sk14AfMirGrRtGoBmL3WM4/AFX/0ffzgc/zwmDgvKkPUsyOHWE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
